# Generated by Django 4.1.3 on 2022-11-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
